services:
  mongo:
    image: mongo:7
#    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: studentdb

  api:
    build: .                # uses Dockerfile in the current folder
    container_name: student-api
    restart: unless-stopped
    ports:
      - "8080:8080"         # host:container
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/studentdb